name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Assuming tests might need pytest and linting needs pre-commit
          pip install pytest pre-commit
          pip install -e .
      - name: Run pre-commit hooks (if config exists)
        run: pre-commit run --all-files || echo "No pre-commit config or hooks failed"
      - name: Run tests (if tests dir exists)
        run: pytest tests/ || echo "No tests found or tests failed"
