name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -e .[test] # Assuming a [test] extra for dev deps
          # If no extras, install manually: pip install -e . && pip install pytest pre-commit
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      - name: Run tests
        run: pytest tests/ # Assuming tests are in a 'tests' directory
